// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pellcomp
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Learners operations.
    /// </summary>
    public partial interface ILearners
    {
        /// <summary>
        /// Search for learners.
        /// </summary>
        /// <param name='searchOptionsfirstname'>
        /// </param>
        /// <param name='searchOptionssurname'>
        /// </param>
        /// <param name='searchOptionspostcode'>
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<IList<TraineeDTO>>> SearchAsyncWithHttpMessagesAsync(string searchOptionsfirstname = default(string), string searchOptionssurname = default(string), string searchOptionspostcode = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
