// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pellcomp
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Learners.
    /// </summary>
    public static partial class LearnersExtensions
    {
            /// <summary>
            /// Search for learners.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchOptionsfirstname'>
            /// </param>
            /// <param name='searchOptionssurname'>
            /// </param>
            /// <param name='searchOptionspostcode'>
            /// </param>
            public static IList<TraineeDTO> SearchAsync(this ILearners operations, string searchOptionsfirstname = default(string), string searchOptionssurname = default(string), string searchOptionspostcode = default(string))
            {
                return operations.SearchAsyncAsync(searchOptionsfirstname, searchOptionssurname, searchOptionspostcode).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Search for learners.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='searchOptionsfirstname'>
            /// </param>
            /// <param name='searchOptionssurname'>
            /// </param>
            /// <param name='searchOptionspostcode'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TraineeDTO>> SearchAsyncAsync(this ILearners operations, string searchOptionsfirstname = default(string), string searchOptionssurname = default(string), string searchOptionspostcode = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.SearchAsyncWithHttpMessagesAsync(searchOptionsfirstname, searchOptionssurname, searchOptionspostcode, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
