// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pellcomp.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MainAimDTO
    {
        /// <summary>
        /// Initializes a new instance of the MainAimDTO class.
        /// </summary>
        public MainAimDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MainAimDTO class.
        /// </summary>
        public MainAimDTO(string level = default(string), string reference = default(string), string title = default(string))
        {
            Level = level;
            Reference = reference;
            Title = title;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Level")]
        public string Level { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Reference")]
        public string Reference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

    }
}
