// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pellcomp.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OfficerDTO
    {
        /// <summary>
        /// Initializes a new instance of the OfficerDTO class.
        /// </summary>
        public OfficerDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OfficerDTO class.
        /// </summary>
        public OfficerDTO(AddressDTO address = default(AddressDTO), string allowedContactMethods = default(string), string code = default(string), string email = default(string), string forename = default(string), string mobile = default(string), string preferredContactMethod = default(string), string roles = default(string), string surname = default(string), string sysStatus = default(string), string telephone = default(string), string username = default(string))
        {
            Address = address;
            AllowedContactMethods = allowedContactMethods;
            Code = code;
            Email = email;
            Forename = forename;
            Mobile = mobile;
            PreferredContactMethod = preferredContactMethod;
            Roles = roles;
            Surname = surname;
            SysStatus = sysStatus;
            Telephone = telephone;
            Username = username;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public AddressDTO Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllowedContactMethods")]
        public string AllowedContactMethods { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Forename")]
        public string Forename { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Mobile")]
        public string Mobile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PreferredContactMethod")]
        public string PreferredContactMethod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Roles")]
        public string Roles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Surname")]
        public string Surname { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SysStatus")]
        public string SysStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Telephone")]
        public string Telephone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Username")]
        public string Username { get; set; }

    }
}
